# Generated by Django 5.0.1 on 2024-03-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='certificado_antecedentes_archivo',
            field=models.FileField(default='', upload_to='static/img/certificados_antecedentes/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='certificado_presentado_afp',
            field=models.FileField(default='', upload_to='static/img/certificados_afp/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='certificado_presentado_salud_archivo',
            field=models.FileField(default='', upload_to='static/img/certificados_salud/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='copia_carnet_archivo',
            field=models.FileField(default='', upload_to='static/img/copias_carnet/'),
        ),
    ]
